/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gestor_alimentacion.view;

import com.gestor_alimentacion.view.components.RegistroAlimentacionForm;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author adm
 */
public class AlimentacionView extends javax.swing.JFrame {

    /**
     * Creates new form AlimentacionView
     */
    public AlimentacionView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jColorChooser1 = new javax.swing.JColorChooser();
        jColorChooser2 = new javax.swing.JColorChooser();
        jColorChooser3 = new javax.swing.JColorChooser();
        jColorChooser4 = new javax.swing.JColorChooser();
        jColorChooser5 = new javax.swing.JColorChooser();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnRegistrarAlimentacion = new javax.swing.JButton();
        btnHistorialAlimentacion = new javax.swing.JButton();
        btnGestionarAlimentos = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(234, 227, 161));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegistrarAlimentacion.setBackground(new java.awt.Color(0, 204, 51));
        btnRegistrarAlimentacion.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        btnRegistrarAlimentacion.setText("Registrar Alimentación");
        btnRegistrarAlimentacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarAlimentacionActionPerformed(evt);
            }
        });
        jPanel3.add(btnRegistrarAlimentacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 260, 38));

        btnHistorialAlimentacion.setBackground(new java.awt.Color(0, 0, 204));
        btnHistorialAlimentacion.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btnHistorialAlimentacion.setForeground(new java.awt.Color(255, 255, 255));
        btnHistorialAlimentacion.setText("Historial");
        btnHistorialAlimentacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistorialAlimentacionActionPerformed(evt);
            }
        });
        jPanel3.add(btnHistorialAlimentacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 260, 40));

        btnGestionarAlimentos.setBackground(new java.awt.Color(0, 0, 204));
        btnGestionarAlimentos.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btnGestionarAlimentos.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionarAlimentos.setText("Gestionar Alimentos");
        btnGestionarAlimentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarAlimentosActionPerformed(evt);
            }
        });
        jPanel3.add(btnGestionarAlimentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 260, 40));

        jPanel2.setBackground(new java.awt.Color(102, 51, 0));
        jPanel2.setToolTipText("");

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Gestor Alimentación ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(326, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 31, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    private void btnGestionarAlimentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarAlimentosActionPerformed
       System.out.println("¡Botón Gestionar Alimentos presionado!");
    // Crea una instancia del panel de gestión de alimentos
    GestionarAlimentosPanel gestionarAlimentosPanel = new GestionarAlimentosPanel();

    // Crea un nuevo JFrame para mostrar el panel
    JFrame gestionarAlimentosFrame = new JFrame("Gestionar Alimentos");
    gestionarAlimentosFrame.getContentPane().add(gestionarAlimentosPanel);
    gestionarAlimentosFrame.pack(); // Ajusta el tamaño de la ventana al panel
    gestionarAlimentosFrame.setLocationRelativeTo(null); // Centra la ventana
    gestionarAlimentosFrame.setVisible(true);
    }//GEN-LAST:event_btnGestionarAlimentosActionPerformed

    private void btnRegistrarAlimentacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarAlimentacionActionPerformed
        System.out.println("¡Botón Registrar Alimentación presionado!");
       // Crea una instancia del formulario de registro
    RegistroAlimentacionForm registroForm = new RegistroAlimentacionForm();

    // Crea un nuevo JFrame para mostrar el formulario
    JFrame registroFrame = new JFrame("Registrar Alimentación");
    registroFrame.getContentPane().add(registroForm);
    registroFrame.pack(); // Ajusta el tamaño de la ventana al formulario
    registroFrame.setLocationRelativeTo(this); // Centra la ventana relativa a AlimentacionView
    registroFrame.setVisible(true);  
        
    }//GEN-LAST:event_btnRegistrarAlimentacionActionPerformed

    
    private void btnHistorialAlimentacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialAlimentacionActionPerformed
  
    }//GEN-LAST:event_btnHistorialAlimentacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlimentacionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlimentacionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlimentacionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlimentacionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlimentacionView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGestionarAlimentos;
    private javax.swing.JButton btnHistorialAlimentacion;
    private javax.swing.JButton btnRegistrarAlimentacion;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JColorChooser jColorChooser2;
    private javax.swing.JColorChooser jColorChooser3;
    private javax.swing.JColorChooser jColorChooser4;
    private javax.swing.JColorChooser jColorChooser5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
