/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.gestor_alimentacion.view;

import com.gestor_alimentacion.model.Alimento;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author adm
 */
public class GestionarAlimentosPanel extends javax.swing.JPanel {

    private JLabel lblNombre; // Ejemplo de etiqueta (si tienes una)
    private JTextField txtNombreAlimento; // Campo de texto para el nombre
    private JLabel lblDescripcion; // Ejemplo de etiqueta
    private JTextArea txtDescripcionAlimento; // Área de texto para la descripción
    private JTable tablaAlimentos; // Tabla para listar alimentos
    private JButton btnNuevoAlimento;
    private JButton btnGuardarAlimento;
    private JButton btnEliminarAlimento;
    
    public GestionarAlimentosPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnEliminarAlimentoAction = new javax.swing.JButton();
        btnGuardarAlimentoAction = new javax.swing.JButton();
        Nuevo = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(255, 239, 224));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setForeground(new java.awt.Color(153, 51, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEliminarAlimentoAction.setBackground(new java.awt.Color(255, 0, 0));
        btnEliminarAlimentoAction.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminarAlimentoAction.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarAlimentoAction.setText("Eliminar");
        btnEliminarAlimentoAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarAlimentoActionActionPerformed(evt);
            }
        });
        jPanel2.add(btnEliminarAlimentoAction, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 90, 30));

        btnGuardarAlimentoAction.setBackground(new java.awt.Color(0, 255, 51));
        btnGuardarAlimentoAction.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btnGuardarAlimentoAction.setText("Guardar");
        btnGuardarAlimentoAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarAlimentoActionActionPerformed(evt);
            }
        });
        jPanel2.add(btnGuardarAlimentoAction, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 90, 30));

        Nuevo.setBackground(new java.awt.Color(0, 0, 255));
        Nuevo.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        Nuevo.setForeground(new java.awt.Color(255, 255, 255));
        Nuevo.setText("Nuevo");
        Nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoActionPerformed(evt);
            }
        });
        jPanel2.add(Nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 90, 30));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 160, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel2.setText("Descripción");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 170, -1));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel4.setText("Nombre");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jPanel1.setBackground(new java.awt.Color(102, 51, 0));
        jPanel1.setForeground(new java.awt.Color(102, 51, 0));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Gestionar alimentos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
     txtDescripcionAlimento.requestFocusInWindow();
    
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoActionPerformed
       // Ahora estas variables deberían ser accesibles
        txtNombreAlimento.setText("");
        txtDescripcionAlimento.setText("");
        if (tablaAlimentos != null) {
            tablaAlimentos.clearSelection();
        }
    
    }//GEN-LAST:event_NuevoActionPerformed

    private void btnGuardarAlimentoActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarAlimentoActionActionPerformed
 // 1. Recuperar los datos ingresados por el usuario
    String nombreAlimento = txtNombreAlimento.getText();
    String descripcionAlimento = txtDescripcionAlimento.getText();

   
  if (nombreAlimento.trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "El nombre del alimento es obligatorio.", "Error", JOptionPane.ERROR_MESSAGE);
        return; // Detener si la validación falla
    }
     // 3. Imprimir los datos en la consola (similar a Registrar Alimentación)
    System.out.println("--- Datos a Guardar (Gestionar Alimentos) ---");
    System.out.println("Nombre: " + nombreAlimento);
    System.out.println("Descripción: " + descripcionAlimento);
    System.out.println("---------------------------------------------");
       
  

    }//GEN-LAST:event_btnGuardarAlimentoActionActionPerformed

    private void btnEliminarAlimentoActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarAlimentoActionActionPerformed
        // *** Aquí iría la lógica para eliminar el alimento seleccionado ***
    // Primero, tendrías que determinar qué alimento se va a eliminar
    // (probablemente basado en una selección en una tabla).

    // Por ahora, simplemente mostraremos un mensaje
    String nombreAEliminar = txtNombreAlimento.getText(); // Ejemplo: eliminar basado en el nombre en el campo

    if (nombreAEliminar.trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, ingrese el nombre del alimento a eliminar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }

    int confirmacion = JOptionPane.showConfirmDialog(this, "¿Seguro que desea eliminar el alimento: " + nombreAEliminar + "?", "Confirmar Eliminación", JOptionPane.YES_NO_OPTION);

    if (confirmacion == JOptionPane.YES_OPTION) {
        // *** Aquí llamarías a tu AlimentoService para eliminar el alimento ***
        // Ejemplo:
        // alimentoService.eliminarAlimentoPorNombre(nombreAEliminar);
        JOptionPane.showMessageDialog(this, "Alimento '" + nombreAEliminar + "' eliminado.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        // Opcional: Limpiar los campos y actualizar la tabla
        txtNombreAlimento.setText("");
        txtDescripcionAlimento.setText("");
        // cargarListaDeAlimentos();
    }
    }//GEN-LAST:event_btnEliminarAlimentoActionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Nuevo;
    private javax.swing.JButton btnEliminarAlimentoAction;
    private javax.swing.JButton btnGuardarAlimentoAction;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    private void cargarTablaAlimentos() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    String getNombreAlimento() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    String getDescripcionAlimento() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    void limpiarCampos() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
