/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.dairy.menu;

import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import java.awt.Color;
import javax.swing.UIManager;

/**
 *
 * @author o.o
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        setSize(1171, 736);
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nombreLogo = new javax.swing.JLabel();
        registroanimales = new javax.swing.JLabel();
        produccionlechera = new javax.swing.JLabel();
        manejoreproductivo = new javax.swing.JLabel();
        alimentacion = new javax.swing.JLabel();
        siete = new javax.swing.JLabel();
        reportes = new javax.swing.JLabel();
        alertas = new javax.swing.JLabel();
        registroanimales1 = new javax.swing.JLabel();
        barra = new javax.swing.JLabel();
        LupaBuscador = new javax.swing.JLabel();
        Buscador2 = new javax.swing.JTextField();
        user = new javax.swing.JLabel();
        registroanimales2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        registroanimales4 = new javax.swing.JLabel();
        registroanimales6 = new javax.swing.JLabel();
        registroanimales3 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        registroanimales5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ManejoReproductivo = new javax.swing.JLabel();
        nombreusuario1 = new javax.swing.JLabel();
        RegistroAnimales = new javax.swing.JLabel();
        ProduccionLechera = new javax.swing.JLabel();
        Alertas = new javax.swing.JLabel();
        Alimentacion = new javax.swing.JLabel();
        Reportes = new javax.swing.JLabel();
        hola1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(226, 237, 207));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombreLogo.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        nombreLogo.setForeground(new java.awt.Color(255, 255, 255));
        nombreLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreLogo.setText("DairySync");
        jPanel1.add(nombreLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 100, 50));

        registroanimales.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registroanimales.setIcon(new FlatSVGIcon(getClass().getResource("/Iconos/alerta2.svg")));
        jPanel1.add(registroanimales, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 450, 200, 190));

        produccionlechera.setBackground(new java.awt.Color(126, 143, 74));
        produccionlechera.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        produccionlechera.setIcon(new FlatSVGIcon(getClass().getResource("/Iconos/leche.svg")));
        produccionlechera.setOpaque(true);
        produccionlechera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                produccionlecheraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                produccionlecheraMouseExited(evt);
            }
        });
        jPanel1.add(produccionlechera, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 100, 50));

        manejoreproductivo.setBackground(new java.awt.Color(126, 143, 74));
        manejoreproductivo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        manejoreproductivo.setIcon(new FlatSVGIcon(getClass().getResource("/Iconos/grafico.svg")));
        manejoreproductivo.setOpaque(true);
        manejoreproductivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                manejoreproductivoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                manejoreproductivoMouseExited(evt);
            }
        });
        jPanel1.add(manejoreproductivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 100, 50));

        alimentacion.setBackground(new java.awt.Color(126, 143, 74));
        alimentacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        alimentacion.setIcon(new FlatSVGIcon(getClass().getResource("/Iconos/alimentos.svg")));
        alimentacion.setOpaque(true);
        alimentacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                alimentacionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                alimentacionMouseExited(evt);
            }
        });
        jPanel1.add(alimentacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 100, 50));

        siete.setIcon(new FlatSVGIcon(getClass().getResource("/Iconos/salir.svg")));
        jPanel1.add(siete, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 660, 80, 50));

        reportes.setBackground(new java.awt.Color(126, 143, 74));
        reportes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reportes.setIcon(new FlatSVGIcon(getClass().getResource("/Iconos/alerta.svg")));
        reportes.setOpaque(true);
        reportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reportesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reportesMouseExited(evt);
            }
        });
        jPanel1.add(reportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 100, 50));

        alertas.setBackground(new java.awt.Color(126, 143, 74));
        alertas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        alertas.setIcon(new FlatSVGIcon(getClass().getResource("/Iconos/doc.svg")));
        alertas.setOpaque(true);
        alertas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                alertasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                alertasMouseExited(evt);
            }
        });
        jPanel1.add(alertas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 100, 50));

        registroanimales1.setBackground(new java.awt.Color(126, 143, 74));
        registroanimales1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registroanimales1.setIcon(new FlatSVGIcon(getClass().getResource("/Iconos/animales.svg")));
        registroanimales1.setOpaque(true);
        registroanimales1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registroanimales1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registroanimales1MouseExited(evt);
            }
        });
        jPanel1.add(registroanimales1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 100, 50));

        barra.setBackground(new java.awt.Color(126, 143, 74));
        barra.setOpaque(true);
        jPanel1.add(barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 740));

        LupaBuscador.setBackground(new java.awt.Color(204, 204, 204));
        LupaBuscador.setIcon(new FlatSVGIcon(getClass().getResource("/Iconos/buscar.svg")));
        jPanel1.add(LupaBuscador, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 40, 40));

        Buscador2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Buscador2.setMargin(new java.awt.Insets(0, 40, 0, 20));
        Buscador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buscador2ActionPerformed(evt);
            }
        });
        jPanel1.add(Buscador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 570, 40));

        user.setIcon(new FlatSVGIcon(getClass().getResource("/Iconos/user2.svg")));
        jPanel1.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 20, 80, 60));

        registroanimales2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registroanimales2.setIcon(new FlatSVGIcon(getClass().getResource("/Iconos/ali2.svg")));
        jPanel1.add(registroanimales2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 450, 200, 190));

        jLabel13.setIcon(new FlatSVGIcon(getClass().getResource("/Iconos/flecha.svg")));
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 590, 70, 30));

        registroanimales4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registroanimales4.setIcon(new FlatSVGIcon(getClass().getResource("/Iconos/aler2.svg")));
        jPanel1.add(registroanimales4, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 200, 200, 190));

        registroanimales6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registroanimales6.setIcon(new FlatSVGIcon(getClass().getResource("/Iconos/doc2.svg")));
        jPanel1.add(registroanimales6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 460, 200, 190));

        registroanimales3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registroanimales3.setIcon(new FlatSVGIcon(getClass().getResource("/Iconos/leche2.svg")));
        jPanel1.add(registroanimales3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, 200, 190));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Lechera");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 270, 230, 40));

        registroanimales5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registroanimales5.setIcon(new FlatSVGIcon(getClass().getResource("/Iconos/ani2.svg")));
        jPanel1.add(registroanimales5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 200, 190));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Producción ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, 160, 40));

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Reproductivo");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 270, 230, 40));

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Alimentación ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 510, 160, 40));

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Manejo");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 230, 160, 40));

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Reportes");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 510, 160, 40));

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Alertas");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 510, 160, 40));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("de Animales");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 230, 40));

        jLabel18.setIcon(new FlatSVGIcon(getClass().getResource("/Iconos/flecha.svg")));
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 340, 70, 30));

        jLabel19.setIcon(new FlatSVGIcon(getClass().getResource("/Iconos/flecha.svg")));
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 600, 70, 30));

        jLabel20.setIcon(new FlatSVGIcon(getClass().getResource("/Iconos/flecha.svg")));
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 340, 70, 30));

        jLabel21.setIcon(new FlatSVGIcon(getClass().getResource("/Iconos/flecha.svg")));
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 590, 70, 30));

        jLabel22.setIcon(new FlatSVGIcon(getClass().getResource("/Iconos/flecha.svg")));
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 336, 70, 30));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registro");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 160, 40));

        ManejoReproductivo.setBackground(new java.awt.Color(126, 143, 74));
        ManejoReproductivo.setOpaque(true);
        ManejoReproductivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ManejoReproductivoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ManejoReproductivoMouseExited(evt);
            }
        });
        jPanel1.add(ManejoReproductivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 190, 290, 190));

        nombreusuario1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        nombreusuario1.setForeground(new java.awt.Color(102, 102, 102));
        nombreusuario1.setText("Nombre de usuario");
        jPanel1.add(nombreusuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 40, -1, -1));

        RegistroAnimales.setBackground(new java.awt.Color(126, 143, 74));
        RegistroAnimales.setOpaque(true);
        RegistroAnimales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RegistroAnimalesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RegistroAnimalesMouseExited(evt);
            }
        });
        jPanel1.add(RegistroAnimales, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 290, 190));

        ProduccionLechera.setBackground(new java.awt.Color(126, 143, 74));
        ProduccionLechera.setOpaque(true);
        ProduccionLechera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ProduccionLecheraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ProduccionLecheraMouseExited(evt);
            }
        });
        jPanel1.add(ProduccionLechera, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, 290, 190));

        Alertas.setBackground(new java.awt.Color(126, 143, 74));
        Alertas.setOpaque(true);
        Alertas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AlertasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AlertasMouseExited(evt);
            }
        });
        jPanel1.add(Alertas, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 440, 290, 190));

        Alimentacion.setBackground(new java.awt.Color(126, 143, 74));
        Alimentacion.setOpaque(true);
        Alimentacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AlimentacionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AlimentacionMouseExited(evt);
            }
        });
        jPanel1.add(Alimentacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 440, 290, 190));

        Reportes.setBackground(new java.awt.Color(126, 143, 74));
        Reportes.setOpaque(true);
        Reportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ReportesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ReportesMouseExited(evt);
            }
        });
        jPanel1.add(Reportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 440, 290, 190));

        hola1.setBackground(new java.awt.Color(126, 143, 74));
        hola1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        hola1.setForeground(new java.awt.Color(126, 143, 74));
        hola1.setText("¡Bienvenido, Nombre Usuario!");
        jPanel1.add(hola1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 380, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1171, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Buscador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buscador2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Buscador2ActionPerformed

    private void RegistroAnimalesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistroAnimalesMouseEntered
   
    }//GEN-LAST:event_RegistroAnimalesMouseEntered

    private void RegistroAnimalesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistroAnimalesMouseExited
     
    }//GEN-LAST:event_RegistroAnimalesMouseExited

    private void ProduccionLecheraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProduccionLecheraMouseEntered
         
    }//GEN-LAST:event_ProduccionLecheraMouseEntered

    private void ProduccionLecheraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProduccionLecheraMouseExited
       
    }//GEN-LAST:event_ProduccionLecheraMouseExited

    private void ManejoReproductivoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManejoReproductivoMouseEntered

    }//GEN-LAST:event_ManejoReproductivoMouseEntered

    private void ManejoReproductivoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManejoReproductivoMouseExited
     
    }//GEN-LAST:event_ManejoReproductivoMouseExited

    private void AlimentacionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AlimentacionMouseEntered
 
    }//GEN-LAST:event_AlimentacionMouseEntered

    private void AlimentacionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AlimentacionMouseExited
      
    }//GEN-LAST:event_AlimentacionMouseExited

    private void ReportesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReportesMouseEntered
    
    }//GEN-LAST:event_ReportesMouseEntered

    private void ReportesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReportesMouseExited
     
    }//GEN-LAST:event_ReportesMouseExited

    private void AlertasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AlertasMouseEntered
      
    }//GEN-LAST:event_AlertasMouseEntered

    private void AlertasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AlertasMouseExited
 
    }//GEN-LAST:event_AlertasMouseExited

    private void registroanimales1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registroanimales1MouseEntered
        registroanimales1.setBackground(new Color(69,82,29));
    }//GEN-LAST:event_registroanimales1MouseEntered

    private void registroanimales1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registroanimales1MouseExited
         registroanimales1.setBackground(new Color(126,143,74));
    }//GEN-LAST:event_registroanimales1MouseExited

    private void produccionlecheraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_produccionlecheraMouseEntered
       produccionlechera.setBackground(new Color(69,82,29));
    }//GEN-LAST:event_produccionlecheraMouseEntered

    private void produccionlecheraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_produccionlecheraMouseExited
        produccionlechera.setBackground(new Color(126,143,74));
    }//GEN-LAST:event_produccionlecheraMouseExited

    private void manejoreproductivoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manejoreproductivoMouseEntered
        manejoreproductivo.setBackground(new Color(69,82,29));
    }//GEN-LAST:event_manejoreproductivoMouseEntered

    private void manejoreproductivoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manejoreproductivoMouseExited
        manejoreproductivo.setBackground(new Color(126,143,74));
    }//GEN-LAST:event_manejoreproductivoMouseExited

    private void alimentacionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alimentacionMouseEntered
       alimentacion.setBackground(new Color(69,82,29));
    }//GEN-LAST:event_alimentacionMouseEntered

    private void alimentacionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alimentacionMouseExited
       alimentacion.setBackground(new Color(126,143,74));
    }//GEN-LAST:event_alimentacionMouseExited

    private void reportesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportesMouseEntered
        reportes.setBackground(new Color(69,82,29));
    }//GEN-LAST:event_reportesMouseEntered

    private void reportesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportesMouseExited
       reportes.setBackground(new Color(126,143,74));
    }//GEN-LAST:event_reportesMouseExited

    private void alertasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alertasMouseEntered
        alertas.setBackground(new Color(69,82,29));
    }//GEN-LAST:event_alertasMouseEntered

    private void alertasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alertasMouseExited
        alertas.setBackground(new Color(126,143,74));
    }//GEN-LAST:event_alertasMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       try {
            
          FlatLightLaf.setup();
         UIManager.put("Component.innerFocusWidth", 3);
         // UIManager.put("TextComponent.arc", 999);
           
        } catch (Exception ex) {
            System.err.println("No se pudo cargar el tema FlatLaf MacOS Light.");
            ex.printStackTrace();
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Alertas;
    private javax.swing.JLabel Alimentacion;
    private javax.swing.JTextField Buscador2;
    private javax.swing.JLabel LupaBuscador;
    private javax.swing.JLabel ManejoReproductivo;
    private javax.swing.JLabel ProduccionLechera;
    private javax.swing.JLabel RegistroAnimales;
    private javax.swing.JLabel Reportes;
    private javax.swing.JLabel alertas;
    private javax.swing.JLabel alimentacion;
    private javax.swing.JLabel barra;
    private javax.swing.JLabel hola1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel manejoreproductivo;
    private javax.swing.JLabel nombreLogo;
    private javax.swing.JLabel nombreusuario1;
    private javax.swing.JLabel produccionlechera;
    private javax.swing.JLabel registroanimales;
    private javax.swing.JLabel registroanimales1;
    private javax.swing.JLabel registroanimales2;
    private javax.swing.JLabel registroanimales3;
    private javax.swing.JLabel registroanimales4;
    private javax.swing.JLabel registroanimales5;
    private javax.swing.JLabel registroanimales6;
    private javax.swing.JLabel reportes;
    private javax.swing.JLabel siete;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
